#!/usr/bin/env python

import os
import sys

## GETTING-STARTED: make sure the next line points to your settings.py:
os.environ['DJANGO_SETTINGS_MODULE'] = 'checkin2015.settings'
## GETTING-STARTED: make sure the next line points to your django project dir:
sys.path.append(os.environ['OPENSHIFT_REPO_DIR'])
from distutils.sysconfig import get_python_lib
os.environ['PYTHON_EGG_CACHE'] = get_python_lib()

import django.core.wsgi
application = django.core.wsgi.get_wsgi_application()